[package]
name = "pindash-news"
version = "0.1.0"
edition = "2021"

[features]
wgpu = []

[dependencies]
anyhow = "1.0.66"
eframe = { path = "../../egui/crates/eframe", features = ["wgpu"] }
egui_extras = { path = "../../egui/crates/egui_extras", features = [
  "svg",
  "image",
] }
image = { version = "0.24.5", default-features = false, features = ["png"] }
once_cell = "1.16.0"
r2d2 = "0.8.10"
r2d2_sqlite = "0.21.0"
rss = {version = "2.0.1", features = ["validation", "with-serde", "atom"] }
rusqlite = { version = "0.28.0", features = ["bundled"] }
rusqlite_migration = "1.0.1"
serde = { version = "1.0.151", features = ["derive"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
