CREATE TABLE IF NOT EXISTS folders (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at INTEGER NOT NULL DEFAULT (
    CAST(
      ROUND((julianday('now') - 2440587.5) * 86400000) As INTEGER
    )
  ),
  updated_at INTEGER NOT NULL DEFAULT (
    CAST(
      ROUND((julianday('now') - 2440587.5) * 86400000) As INTEGER
    )
  )
);

CREATE TABLE IF NOT EXISTS folder_sources (
  f INTEGER NOT NULL REFERENCES folders(id) ON DELETE CASCADE ON UPDATE CASCADE,
  s INTEGER NOT NULL REFERENCES sources(id) ON DELETE CASCADE ON UPDATE CASCADE,
  PRIMARY KEY(f, s)
);