ALTER TABLE feeds DROP COLUMN author;

CREATE TABLE IF NOT EXISTS authors (
  id INTEGER PRIMARY KEY,
  source_id INTEGER NOT NULL REFERENCES sources(id) ON DELETE CASCADE ON UPDATE CASCADE,
  name TEXT NOT NULL,
  email TEXT,
  url TEXT,
  created INTEGER NOT NULL DEFAULT (
    CAST(
      ROUND((julianday('now') - 2440587.5) * 86400000) As INTEGER
    )
  ),
  UNIQUE(source_id, name)
);

CREATE TABLE IF NOT EXISTS feed_authors (
  f INTEGER NOT NULL REFERENCES feeds(id) ON DELETE CASCADE ON UPDATE CASCADE,
  a INTEGER NOT NULL REFERENCES authors(id) ON DELETE CASCADE ON UPDATE CASCADE,
  PRIMARY KEY(f, a)
);